package swiftteams.nikitin.sql.runtime;

/*Generated by MPS */

import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ArrayListCreator {

  public ArrayListCreator() {
  }

  public static ArrayList<TableRow> create(ResultSet resultSet) throws SQLException {
    resultSet.last();
    int size = resultSet.getRow();
    Debug.debug("size: " + size);
    ArrayList<TableRow> rows = new ArrayList<TableRow>(size);
    for(int i = 0 ; i < size ; i++ ) {
      resultSet.absolute(i + 1);
      rows.add(new TableRow(resultSet));
    }
    return rows;
  }

}
