package mathcentre.nikitin.chat;

/*Generated by MPS */


public class Const {
  public static int serverPort = 239;
  public static String serverMsg = "<server msg";
  public static String greeting = "-= PREVED, PREDMED!!! =- MPS";
  public static String authReq = "[Enter your nickname]";
  public static String enterNotify = " entered the chat]";
  public static String leaveNotify = " has left the chat]";
  public static String prefix = "[";
  public static String separator = "> ";
  public static String threatNotify = "'s name was threaten to be used by someone else]";

  public Const() {
  }
}
