package mathcentre.nikitin.chat;

/*Generated by MPS */

import java.sql.SQLException;
import swiftteams.nikitin.sql.runtime.ConnectionManager;
import swiftteams.nikitin.sql.runtime.TableRow;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import swiftteams.nikitin.sql.runtime.ArrayListCreator;
import java.sql.Timestamp;

public class HistoryViewer {

  public HistoryViewer() {
  }

  public static void main(String[] args) throws SQLException {
    ConnectionManager.setConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/chat", "Morj", "abacaba");
    for(TableRow element : ListSequence.fromList(ArrayListCreator.create(ConnectionManager.query("SELECT   * FROM " + "" + "history" + "   " + "" + "ORDER BY" + " " + "history.timestamp")))) {
      System.out.println(Server.getTime(((Timestamp)element.getProperty("timestamp"))) + " " + ((String)element.getProperty("login")) + Const.separator + ((String)element.getProperty("message")));
    }
  }

}
