package swiftteams.nikitin.sql.generator.baseLanguage.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNode;
import swiftteams.nikitin.sql.generator.baseLanguage.template.transformation.util.TransformationHelper;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.typesystem.inference.TypeChecker;

public class QueriesGenerated {

  public static boolean baseMappingRule_Condition_1217435464842(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(_context.getNode(), "operation", true)), "swiftteams.nikitin.sql.structure.TableRowsAccessOperation");
  }

  public static boolean baseMappingRule_Condition_1217493036533(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(_context.getNode(), "lValue", true)), "jetbrains.mps.baseLanguage.structure.DotExpression") && SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "lValue", true), "jetbrains.mps.baseLanguage.structure.DotExpression"), "operation", true)), "swiftteams.nikitin.sql.structure.TableRowsAccessOperation");
  }

  public static boolean baseMappingRule_Condition_1217496442117(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return !(SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SNodeOperations.getParent(_context.getNode())), "swiftteams.nikitin.sql.structure.ColumnRelationalProperty"));
  }

  public static boolean baseMappingRule_Condition_1217496537609(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return !(SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SNodeOperations.getParent(_context.getNode())), "swiftteams.nikitin.sql.structure.ColumnRelationalProperty"));
  }

  public static boolean baseMappingRule_Condition_1218011410690(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return !(SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SNodeOperations.getParent(_context.getNode())), "swiftteams.nikitin.sql.structure.ColumnRelationalProperty"));
  }

  public static boolean baseMappingRule_Condition_1218021030637(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return !(SConceptOperations.isExactly(SNodeOperations.getConceptDeclaration(SNodeOperations.getParent(_context.getNode())), "swiftteams.nikitin.sql.structure.ColumnRelationalProperty"));
  }

  public static Object propertyMacro_GetPropertyValue_1217498326260(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217510244048(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "operation", true), "swiftteams.nikitin.sql.structure.TableRowsAccessOperation"), "column", false), "columnName");
  }

  public static Object propertyMacro_GetPropertyValue_1217511471819(final IOperationContext operationContext, final PropertyMacroContext _context) {
    SNode operation = SNodeOperations.cast(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "lValue", true), "jetbrains.mps.baseLanguage.structure.DotExpression"), "operation", true), "swiftteams.nikitin.sql.structure.TableRowsAccessOperation");
    return SPropertyOperations.getString(SLinkOperations.getTarget(operation, "column", false), "columnName");
  }

  public static Object propertyMacro_GetPropertyValue_1217581626894(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217600985879(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217602650252(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "modifier", "NOT NULL");
  }

  public static Object propertyMacro_GetPropertyValue_1217841579825(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "column", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217856619588(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "table", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217926912537(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "column", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217927598320(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "column", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217930622355(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "column", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1217931725165(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "where_condition", true) != null)) {
      return "WHERE ";
    } else
    {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_1217931818308(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "having_condition", true) != null)) {
      return "HAVING";
    } else
    {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_1217931916984(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "subquery", true) != null)) {
      return SPropertyOperations.getString_def(_context.getNode(), "subquerymodifier", "UNION");
    } else
    {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_1217932046642(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "modifier", " ");
  }

  public static Object propertyMacro_GetPropertyValue_1218008985182(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "c_alias");
  }

  public static Object propertyMacro_GetPropertyValue_1218010055291(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "join_type", " ");
  }

  public static Object propertyMacro_GetPropertyValue_1218014404106(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "reference", true), "table", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1218014421138(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "data", true), "column", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1218014656519(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "operator", "=");
  }

  public static Object propertyMacro_GetPropertyValue_1218021340646(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "expr", true) != null)) {
      return "DEFAULT";
    } else
    {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_1218106769816(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "where_condition", true) != null)) {
      return " WHERE ";
    } else
    {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_1218107356693(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(_context.getNode(), "opeartor", "AND");
  }

  public static Object propertyMacro_GetPropertyValue_1218112049801(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return TransformationHelper.getParameterName(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_1218120802627(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return TransformationHelper.getParameterName(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_1218128492103(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "column", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1218184084813(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return TransformationHelper.getParameterName(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_1218198194042(final IOperationContext operationContext, final PropertyMacroContext _context) {
    if ((SLinkOperations.getTarget(_context.getNode(), "having_condition", true) != null)) {
      return " HAVING ";
    } else
    {
      return "";
    }
  }

  public static Object propertyMacro_GetPropertyValue_1218446178847(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return Integer.toString(SPropertyOperations.getInteger(_context.getNode(), "maxlen"));
  }

  public static SNode sourceNodeQuery_1217426238424(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "table_insert", true);
  }

  public static SNode sourceNodeQuery_1217426605291(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "insert_into_clause", true);
  }

  public static SNode sourceNodeQuery_1217426612873(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "subquery", true);
  }

  public static SNode sourceNodeQuery_1217505853174(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SNodeOperations.copyNode(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "operation", true), "swiftteams.nikitin.sql.structure.TableRowsAccessOperation"), "column", false), "datatype", true));
  }

  public static SNode sourceNodeQuery_1217510189319(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "operand", true);
  }

  public static SNode sourceNodeQuery_1217511468394(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "lValue", true), "jetbrains.mps.baseLanguage.structure.DotExpression"), "operand", true);
  }

  public static SNode sourceNodeQuery_1217511481698(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "rValue", true);
  }

  public static SNode sourceNodeQuery_1217591737280(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1217595069100(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TransformationHelper.getConcatenationExpression(SLinkOperations.getTargets(_context.getNode(), "strings", true), SPropertyOperations.getString(_context.getNode(), "separator"));
  }

  public static SNode sourceNodeQuery_1217601115088(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "datatype", true);
  }

  public static SNode sourceNodeQuery_1217601217033(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expr", true);
  }

  public static SNode sourceNodeQuery_1217601225839(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "constraint", true);
  }

  public static SNode sourceNodeQuery_1217602528362(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "body", true);
  }

  public static SNode sourceNodeQuery_1217606624752(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }

  public static SNode sourceNodeQuery_1217606774661(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return TransformationHelper.getVarCharWrapper(_context.getNode());
  }

  public static SNode sourceNodeQuery_1217836343892(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1217839943326(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1217839954643(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "insert_into_clause", true);
  }

  public static SNode sourceNodeQuery_1217840241398(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "table_expression_clause", true);
  }

  public static SNode sourceNodeQuery_1217855380329(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1217856570651(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "reference", true);
  }

  public static SNode sourceNodeQuery_1217857173716(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "cascade", true);
  }

  public static SNode sourceNodeQuery_1217857182884(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "table", true);
  }

  public static SNode sourceNodeQuery_1217926677692(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "references_clause", true);
  }

  public static SNode sourceNodeQuery_1217926859104(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "table", true);
  }

  public static SNode sourceNodeQuery_1217931899496(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "where_condition", true);
  }

  public static SNode sourceNodeQuery_1217931906506(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "having_condition", true);
  }

  public static SNode sourceNodeQuery_1217932056808(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "select_list", true);
  }

  public static SNode sourceNodeQuery_1217932100919(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "subquery", true);
  }

  public static SNode sourceNodeQuery_1217934075750(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1217934153169(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expr", true);
  }

  public static SNode sourceNodeQuery_1217947852560(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "subquery", true);
  }

  public static SNode sourceNodeQuery_1218008598610(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "reference", true);
  }

  public static SNode sourceNodeQuery_1218008680460(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1218008994548(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expr", true);
  }

  public static SNode sourceNodeQuery_1218010045606(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "table_reference", true);
  }

  public static SNode sourceNodeQuery_1218010063388(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "joined_table", true);
  }

  public static SNode sourceNodeQuery_1218014650293(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "left", true);
  }

  public static SNode sourceNodeQuery_1218014673432(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "right", true);
  }

  public static SNode sourceNodeQuery_1218106769808(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "table", true);
  }

  public static SNode sourceNodeQuery_1218106769833(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "where_condition", true);
  }

  public static SNode sourceNodeQuery_1218107310221(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "left", true);
  }

  public static SNode sourceNodeQuery_1218107347575(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "right", true);
  }

  public static SNode sourceNodeQuery_1218111730927(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1218113975936(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "condition", true);
  }

  public static SNode sourceNodeQuery_1218120705891(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }

  public static SNode sourceNodeQuery_1218183858426(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expression", true);
  }

  public static SNode sourceNodeQuery_1218187072988(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "subquery", true);
  }

  public static SNode sourceNodeQuery_1218187372300(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "row", true);
  }

  public static SNode sourceNodeQuery_1218194111237(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "type", true), "row", true);
  }

  public static SNode sourceNodeQuery_1218198059639(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "group_by_clause", true);
  }

  public static SNode sourceNodeQuery_1218198159367(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1218198623403(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "having_condition", true);
  }

  public static SNode sourceNodeQuery_1218199767154(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1218199994621(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "order_by_clause", true);
  }

  public static SNode sourceNodeQuery_1236092380003(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "schema", false), "driver", true);
  }

  public static SNode sourceNodeQuery_1236092380011(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "schema", false), "url", true);
  }

  public static SNode sourceNodeQuery_1236092380019(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "schema", false), "login", true);
  }

  public static SNode sourceNodeQuery_1236092380027(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "schema", false), "password", true);
  }

  public static SNode sourceNodeQuery_1236093363079(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "driver", true);
  }

  public static SNode sourceNodeQuery_1236093369255(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "url", true);
  }

  public static SNode sourceNodeQuery_1236093374928(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "login", true);
  }

  public static SNode sourceNodeQuery_1236093379116(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "password", true);
  }

  public static Iterable sourceNodesQuery_1217591721521(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "relational_properties", true);
  }

  public static Iterable sourceNodesQuery_1217836339389(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "values", true);
  }

  public static Iterable sourceNodesQuery_1217839931895(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "values", true);
  }

  public static Iterable sourceNodesQuery_1217840281209(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "columns", true);
  }

  public static Iterable sourceNodesQuery_1217855380321(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "queries", true);
  }

  public static Iterable sourceNodesQuery_1217926871709(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "columns", true);
  }

  public static Iterable sourceNodesQuery_1217927540763(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "columns", true);
  }

  public static Iterable sourceNodesQuery_1217930605987(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "columns", true);
  }

  public static Iterable sourceNodesQuery_1217932069005(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "table_references", true);
  }

  public static Iterable sourceNodesQuery_1217934058659(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "items", true);
  }

  public static Iterable sourceNodesQuery_1218111720234(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "values", true);
  }

  public static Iterable sourceNodesQuery_1218111964111(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SNodeOperations.cast(TypeChecker.getInstance().getTypeOf(_context.getNode()), "swiftteams.nikitin.sql.structure.TableRow"), "parameters", true);
  }

  public static Iterable sourceNodesQuery_1218120752440(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SNodeOperations.cast(TypeChecker.getInstance().getTypeOf(SLinkOperations.getTarget(_context.getNode(), "expression", true)), "swiftteams.nikitin.sql.structure.TableRow"), "parameters", true);
  }

  public static Iterable sourceNodesQuery_1218128470491(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "columns", true);
  }

  public static Iterable sourceNodesQuery_1218183903248(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(SNodeOperations.cast(TypeChecker.getInstance().getTypeOf(SLinkOperations.getTarget(_context.getNode(), "expression", true)), "swiftteams.nikitin.sql.structure.TableRows"), "row", true), "parameters", true);
  }

  public static Iterable sourceNodesQuery_1218198154269(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "expressions", true);
  }

  public static Iterable sourceNodesQuery_1218199763900(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "expressions", true);
  }

  public static Iterable sourceNodesQuery_1236092380036(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "statements", true), "statement", true);
  }

}
