package swiftteams.nikitin.sql.helgins;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.SubtypingRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.ISubtypingRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class tablerows_extends_list_SubtypingRule extends SubtypingRule_Runtime implements ISubtypingRule_Runtime {

  public tablerows_extends_list_SubtypingRule() {
  }

  public SNode getSubOrSuperType(SNode tableRows) {
    return new _Quotations.QuotationClass_10().createNode(SLinkOperations.getTarget(tableRows, "row", true));
  }

  public String getApplicableConceptFQName() {
    return "swiftteams.nikitin.sql.structure.TableRows";
  }

  public boolean isApplicable(SNode argument) {
    return SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
  }

  public boolean isWeak() {
    return false;
  }

}
