package swiftteams.nikitin.sql.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class TableRowsExpression_DataFlow extends DataFlowBuilder {

  public TableRowsExpression_DataFlow() {
  }

  public void build(final IOperationContext operationContext, final DataFlowBuilderContext _context) {
    for(SNode value : ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true))) {
      _context.getBuilder().emitRead(value);
    }
  }

}
