package swiftteams.nikitin.sql.runtime;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;

public class ConnectionManager {
  private static Connection connection;

  public static void setConnection(String driver, String url, String username, String pw) throws SQLException {
    try {
      Class.forName(driver);
    } catch (ClassNotFoundException cnfe) {
      cnfe.printStackTrace();
    } finally {
      connection = DriverManager.getConnection(url, username, pw);
    }
  }

  public static ResultSet query(String query) throws SQLException {
    Debug.debug("was query: " + query);
    ResultSet resultSet = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY).executeQuery(query);
    return resultSet;
  }

  public static int update(String query) throws SQLException {
    Debug.debug("was query: " + query);
    return connection.createStatement().executeUpdate(query);
  }

  public static void shutdown() throws SQLException {
    connection.close();
  }

}
