package swiftteams.nikitin.sql.runtime;

/*Generated by MPS */


public class TableRowExtractor {

  public TableRowExtractor() {
  }

  public static String getPresentation(TableRow tr, String[] names) {
    StringBuilder sb = new StringBuilder();
    for(int i = 0 ; i < names.length ; i++ ) {
      if (i > 0) {
        sb.append(',');
      }
      addSQLWrapper(tr.getProperty(names[i]), sb);
    }
    return sb.toString();
  }

  public static String getPresentation(Iterable<TableRow> tableRows, String[] names) {
    StringBuilder sb = new StringBuilder();
    boolean first = true;
    for(TableRow tr : tableRows) {
      if (first) {
        first = false;
      } else
      {
        sb.append(',');
      }
      sb.append('(');
      sb.append(getPresentation(tr, names));
      sb.append(')');
    }
    return sb.toString();
  }

  private static void addSQLWrapper(Object obj, StringBuilder sb) {
    if (obj instanceof String) {
      sb.append("'");
      sb.append(obj);
      sb.append("'");
    } else
    {
      sb.append(obj);
    }
  }

}
