package swiftteams.nikitin.sql.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilders;
import jetbrains.mps.lang.dataFlow.DataFlowManager;

public class DFABuilders extends DataFlowBuilders {

  public void install(DataFlowManager manager) {
    manager.register("swiftteams.nikitin.sql.structure.TableRowsExpressionValue", new TableRowsExpressionValue_DataFlow());
    manager.register("swiftteams.nikitin.sql.structure.TableRowsExpressionValues", new TableRowsExpressionValues_DataFlow());
    manager.register("swiftteams.nikitin.sql.structure.TableRowsExpression", new TableRowsExpression_DataFlow());
    manager.register("swiftteams.nikitin.sql.structure.JavaSimpleExpression", new JavaSimpleExpression_DataFlow());
  }

}
