package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractInlineConstraintBody extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractInlineConstraintBody";

  public AbstractInlineConstraintBody(SNode node) {
    super(node);
  }

  public static AbstractInlineConstraintBody newInstance(SModel sm, boolean init) {
    return (AbstractInlineConstraintBody)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractInlineConstraintBody", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractInlineConstraintBody newInstance(SModel sm) {
    return AbstractInlineConstraintBody.newInstance(sm, false);
  }

}
