package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractReferencesInlineConstraintBody111 extends AbstractInlineConstraintBody {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractReferencesInlineConstraintBody111";

  public AbstractReferencesInlineConstraintBody111(SNode node) {
    super(node);
  }

  public static AbstractReferencesInlineConstraintBody111 newInstance(SModel sm, boolean init) {
    return (AbstractReferencesInlineConstraintBody111)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractReferencesInlineConstraintBody111", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractReferencesInlineConstraintBody111 newInstance(SModel sm) {
    return AbstractReferencesInlineConstraintBody111.newInstance(sm, false);
  }

}
