package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum BinaryLogicalConditionData {
  and("AND", "AND"),
  or("OR", "OR");

  private String myName;
  private String myValue;

  BinaryLogicalConditionData(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<BinaryLogicalConditionData> getConstants() {
    List<BinaryLogicalConditionData> list = new LinkedList<BinaryLogicalConditionData>();
    list.add(BinaryLogicalConditionData.and);
    list.add(BinaryLogicalConditionData.or);
    return list;
  }

  public static BinaryLogicalConditionData getDefault() {
    return BinaryLogicalConditionData.and;
  }

  public static BinaryLogicalConditionData parseValue(String value) {
    if (value == null) {
      return BinaryLogicalConditionData.getDefault();
    }
    if (value.equals(BinaryLogicalConditionData.and.getValueAsString())) {
      return BinaryLogicalConditionData.and;
    }
    if (value.equals(BinaryLogicalConditionData.or.getValueAsString())) {
      return BinaryLogicalConditionData.or;
    }
    return BinaryLogicalConditionData.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
