package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CaseExpression extends AbstractCaseExpression {
  public static final String concept = "swiftteams.nikitin.sql.structure.CaseExpression";

  public CaseExpression(SNode node) {
    super(node);
  }

  public static CaseExpression newInstance(SModel sm, boolean init) {
    return (CaseExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CaseExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CaseExpression newInstance(SModel sm) {
    return CaseExpression.newInstance(sm, false);
  }

}
