package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompoundCondition extends Condition {
  public static final String concept = "swiftteams.nikitin.sql.structure.CompoundCondition";

  public CompoundCondition(SNode node) {
    super(node);
  }

  public static CompoundCondition newInstance(SModel sm, boolean init) {
    return (CompoundCondition)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CompoundCondition", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompoundCondition newInstance(SModel sm) {
    return CompoundCondition.newInstance(sm, false);
  }

}
