package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompoundExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.CompoundExpression";

  public CompoundExpression(SNode node) {
    super(node);
  }

  public static CompoundExpression newInstance(SModel sm, boolean init) {
    return (CompoundExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CompoundExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompoundExpression newInstance(SModel sm) {
    return CompoundExpression.newInstance(sm, false);
  }

}
