package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompoundSelectList extends SelectList {
  public static final String concept = "swiftteams.nikitin.sql.structure.CompoundSelectList";
  public static final String ITEMS = "items";

  public CompoundSelectList(SNode node) {
    super(node);
  }

  public int getItemsesCount() {
    return this.getChildCount(CompoundSelectList.ITEMS);
  }

  public Iterator<AbstractSelectListItem> itemses() {
    return this.children(AbstractSelectListItem.class, CompoundSelectList.ITEMS);
  }

  public List<AbstractSelectListItem> getItemses() {
    return this.getChildren(AbstractSelectListItem.class, CompoundSelectList.ITEMS);
  }

  public void addItems(AbstractSelectListItem node) {
    this.addChild(CompoundSelectList.ITEMS, node);
  }

  public void insertItems(AbstractSelectListItem prev, AbstractSelectListItem node) {
    this.insertChild(prev, CompoundSelectList.ITEMS, node);
  }


  public static CompoundSelectList newInstance(SModel sm, boolean init) {
    return (CompoundSelectList)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CompoundSelectList", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompoundSelectList newInstance(SModel sm) {
    return CompoundSelectList.newInstance(sm, false);
  }

}
