package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Statement;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.StatementList;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ConnectStatement extends Statement {
  public static final String concept = "swiftteams.nikitin.sql.structure.ConnectStatement";
  public static final String SCHEMA = "schema";
  public static final String STATEMENTS = "statements";

  public ConnectStatement(SNode node) {
    super(node);
  }

  public QuerySheet getSchema() {
    return (QuerySheet)this.getReferent(QuerySheet.class, ConnectStatement.SCHEMA);
  }

  public void setSchema(QuerySheet node) {
    super.setReferent(ConnectStatement.SCHEMA, node);
  }

  public StatementList getStatements() {
    return (StatementList)this.getChild(StatementList.class, ConnectStatement.STATEMENTS);
  }

  public void setStatements(StatementList node) {
    super.setChild(ConnectStatement.STATEMENTS, node);
  }


  public static ConnectStatement newInstance(SModel sm, boolean init) {
    return (ConnectStatement)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ConnectStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ConnectStatement newInstance(SModel sm) {
    return ConnectStatement.newInstance(sm, false);
  }

}
