package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum CreateQueryCommitModifierData {
  ON_COMMIT_DELETE_ROWS("DELETE", "ON COMMIT DELETE ROWS"),
  ON_COMMIT_PRESERVE_ROWS("PRESERVE", "ON COMMIT PRESERVE ROWS");

  private String myName;
  private String myValue;

  CreateQueryCommitModifierData(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<CreateQueryCommitModifierData> getConstants() {
    List<CreateQueryCommitModifierData> list = new LinkedList<CreateQueryCommitModifierData>();
    list.add(CreateQueryCommitModifierData.ON_COMMIT_DELETE_ROWS);
    list.add(CreateQueryCommitModifierData.ON_COMMIT_PRESERVE_ROWS);
    return list;
  }

  public static CreateQueryCommitModifierData getDefault() {
    return CreateQueryCommitModifierData.ON_COMMIT_DELETE_ROWS;
  }

  public static CreateQueryCommitModifierData parseValue(String value) {
    if (value == null) {
      return CreateQueryCommitModifierData.getDefault();
    }
    if (value.equals(CreateQueryCommitModifierData.ON_COMMIT_DELETE_ROWS.getValueAsString())) {
      return CreateQueryCommitModifierData.ON_COMMIT_DELETE_ROWS;
    }
    if (value.equals(CreateQueryCommitModifierData.ON_COMMIT_PRESERVE_ROWS.getValueAsString())) {
      return CreateQueryCommitModifierData.ON_COMMIT_PRESERVE_ROWS;
    }
    return CreateQueryCommitModifierData.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
