package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CreateQuery extends AbstractQuery {
  public static final String concept = "swiftteams.nikitin.sql.structure.CreateQuery";
  public static final String NAME = "name";

  public CreateQuery(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(CreateQuery.NAME);
  }

  public void setName(String value) {
    this.setProperty(CreateQuery.NAME, value);
  }


  public static CreateQuery newInstance(SModel sm, boolean init) {
    return (CreateQuery)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CreateQuery", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CreateQuery newInstance(SModel sm) {
    return CreateQuery.newInstance(sm, false);
  }

}
