package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DataType extends Type {
  public static final String concept = "swiftteams.nikitin.sql.structure.DataType";

  public DataType(SNode node) {
    super(node);
  }

  public static DataType newInstance(SModel sm, boolean init) {
    return (DataType)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.DataType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DataType newInstance(SModel sm) {
    return DataType.newInstance(sm, false);
  }

}
