package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DateDataType extends DataType {
  public static final String concept = "swiftteams.nikitin.sql.structure.DateDataType";

  public DateDataType(SNode node) {
    super(node);
  }

  public static DateDataType newInstance(SModel sm, boolean init) {
    return (DateDataType)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.DateDataType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DateDataType newInstance(SModel sm) {
    return DateDataType.newInstance(sm, false);
  }

}
