package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DefaultValue extends Value {
  public static final String concept = "swiftteams.nikitin.sql.structure.DefaultValue";

  public DefaultValue(SNode node) {
    super(node);
  }

  public static DefaultValue newInstance(SModel sm, boolean init) {
    return (DefaultValue)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.DefaultValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DefaultValue newInstance(SModel sm) {
    return DefaultValue.newInstance(sm, false);
  }

}
