package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ExpressionValue extends Value {
  public static final String concept = "swiftteams.nikitin.sql.structure.ExpressionValue";
  public static final String EXPRESSION = "expression";

  public ExpressionValue(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression)this.getChild(Expression.class, ExpressionValue.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(ExpressionValue.EXPRESSION, node);
  }


  public static ExpressionValue newInstance(SModel sm, boolean init) {
    return (ExpressionValue)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ExpressionValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ExpressionValue newInstance(SModel sm) {
    return ExpressionValue.newInstance(sm, false);
  }

}
