package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IntervalExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.IntervalExpression";

  public IntervalExpression(SNode node) {
    super(node);
  }

  public static IntervalExpression newInstance(SModel sm, boolean init) {
    return (IntervalExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.IntervalExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IntervalExpression newInstance(SModel sm) {
    return IntervalExpression.newInstance(sm, false);
  }

}
