package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum LikeConditionModifier {
  like("LIKE", "LIKE"),
  nlike("NOT LIKE", "NOT LIKE");

  private String myName;
  private String myValue;

  LikeConditionModifier(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<LikeConditionModifier> getConstants() {
    List<LikeConditionModifier> list = new LinkedList<LikeConditionModifier>();
    list.add(LikeConditionModifier.like);
    list.add(LikeConditionModifier.nlike);
    return list;
  }

  public static LikeConditionModifier getDefault() {
    return LikeConditionModifier.like;
  }

  public static LikeConditionModifier parseValue(String value) {
    if (value == null) {
      return LikeConditionModifier.getDefault();
    }
    if (value.equals(LikeConditionModifier.like.getValueAsString())) {
      return LikeConditionModifier.like;
    }
    if (value.equals(LikeConditionModifier.nlike.getValueAsString())) {
      return LikeConditionModifier.nlike;
    }
    return LikeConditionModifier.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
