package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ListMemberShipCondition111 extends MembershipCondition {
  public static final String concept = "swiftteams.nikitin.sql.structure.ListMemberShipCondition111";

  public ListMemberShipCondition111(SNode node) {
    super(node);
  }

  public static ListMemberShipCondition111 newInstance(SModel sm, boolean init) {
    return (ListMemberShipCondition111)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ListMemberShipCondition111", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ListMemberShipCondition111 newInstance(SModel sm) {
    return ListMemberShipCondition111.newInstance(sm, false);
  }

}
