package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Literal extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.Literal";

  public Literal(SNode node) {
    super(node);
  }

  public static Literal newInstance(SModel sm, boolean init) {
    return (Literal)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.Literal", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Literal newInstance(SModel sm) {
    return Literal.newInstance(sm, false);
  }

}
