package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum LiteralConstraintBodyModifierData {
  NOT_NULL("NOT NULL", "NOT NULL"),
  NULL("NULL", "NULL"),
  PRIMARY_KEY("PRIMARY KEY", "PRIMARY KEY");

  private String myName;
  private String myValue;

  LiteralConstraintBodyModifierData(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<LiteralConstraintBodyModifierData> getConstants() {
    List<LiteralConstraintBodyModifierData> list = new LinkedList<LiteralConstraintBodyModifierData>();
    list.add(LiteralConstraintBodyModifierData.NOT_NULL);
    list.add(LiteralConstraintBodyModifierData.NULL);
    list.add(LiteralConstraintBodyModifierData.PRIMARY_KEY);
    return list;
  }

  public static LiteralConstraintBodyModifierData getDefault() {
    return LiteralConstraintBodyModifierData.NOT_NULL;
  }

  public static LiteralConstraintBodyModifierData parseValue(String value) {
    if (value == null) {
      return LiteralConstraintBodyModifierData.getDefault();
    }
    if (value.equals(LiteralConstraintBodyModifierData.NOT_NULL.getValueAsString())) {
      return LiteralConstraintBodyModifierData.NOT_NULL;
    }
    if (value.equals(LiteralConstraintBodyModifierData.NULL.getValueAsString())) {
      return LiteralConstraintBodyModifierData.NULL;
    }
    if (value.equals(LiteralConstraintBodyModifierData.PRIMARY_KEY.getValueAsString())) {
      return LiteralConstraintBodyModifierData.PRIMARY_KEY;
    }
    return LiteralConstraintBodyModifierData.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
