package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum NonListMembershipConditionModifierData {
  in("IN", "IN"),
  nin("NOT IN", "NOT IN");

  private String myName;
  private String myValue;

  NonListMembershipConditionModifierData(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<NonListMembershipConditionModifierData> getConstants() {
    List<NonListMembershipConditionModifierData> list = new LinkedList<NonListMembershipConditionModifierData>();
    list.add(NonListMembershipConditionModifierData.in);
    list.add(NonListMembershipConditionModifierData.nin);
    return list;
  }

  public static NonListMembershipConditionModifierData getDefault() {
    return NonListMembershipConditionModifierData.in;
  }

  public static NonListMembershipConditionModifierData parseValue(String value) {
    if (value == null) {
      return NonListMembershipConditionModifierData.getDefault();
    }
    if (value.equals(NonListMembershipConditionModifierData.in.getValueAsString())) {
      return NonListMembershipConditionModifierData.in;
    }
    if (value.equals(NonListMembershipConditionModifierData.nin.getValueAsString())) {
      return NonListMembershipConditionModifierData.nin;
    }
    return NonListMembershipConditionModifierData.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
