package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum NullConditionModifier {
  nul("IS NULL", "IS NULL"),
  nnul("IS NOT NULL", "IS NOT NULL");

  private String myName;
  private String myValue;

  NullConditionModifier(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<NullConditionModifier> getConstants() {
    List<NullConditionModifier> list = new LinkedList<NullConditionModifier>();
    list.add(NullConditionModifier.nul);
    list.add(NullConditionModifier.nnul);
    return list;
  }

  public static NullConditionModifier getDefault() {
    return NullConditionModifier.nul;
  }

  public static NullConditionModifier parseValue(String value) {
    if (value == null) {
      return NullConditionModifier.getDefault();
    }
    if (value.equals(NullConditionModifier.nul.getValueAsString())) {
      return NullConditionModifier.nul;
    }
    if (value.equals(NullConditionModifier.nnul.getValueAsString())) {
      return NullConditionModifier.nnul;
    }
    return NullConditionModifier.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
