package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ObjectAccessExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.ObjectAccessExpression";

  public ObjectAccessExpression(SNode node) {
    super(node);
  }

  public static ObjectAccessExpression newInstance(SModel sm, boolean init) {
    return (ObjectAccessExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ObjectAccessExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ObjectAccessExpression newInstance(SModel sm) {
    return ObjectAccessExpression.newInstance(sm, false);
  }

}
