package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PKeyConstraint extends AbstractOutLineConstraint {
  public static final String concept = "swiftteams.nikitin.sql.structure.PKeyConstraint";
  public static final String COLUMNS = "columns";

  public PKeyConstraint(SNode node) {
    super(node);
  }

  public int getColumnsesCount() {
    return this.getChildCount(PKeyConstraint.COLUMNS);
  }

  public Iterator<AbstractColumnReference> columnses() {
    return this.children(AbstractColumnReference.class, PKeyConstraint.COLUMNS);
  }

  public List<AbstractColumnReference> getColumnses() {
    return this.getChildren(AbstractColumnReference.class, PKeyConstraint.COLUMNS);
  }

  public void addColumns(AbstractColumnReference node) {
    this.addChild(PKeyConstraint.COLUMNS, node);
  }

  public void insertColumns(AbstractColumnReference prev, AbstractColumnReference node) {
    this.insertChild(prev, PKeyConstraint.COLUMNS, node);
  }


  public static PKeyConstraint newInstance(SModel sm, boolean init) {
    return (PKeyConstraint)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.PKeyConstraint", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PKeyConstraint newInstance(SModel sm) {
    return PKeyConstraint.newInstance(sm, false);
  }

}
