package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum RangeConditionModifier {
  between("BETWEEN", "BETWEEN"),
  nbetween("NOT BETWEEN", "NOT BETWEEN");

  private String myName;
  private String myValue;

  RangeConditionModifier(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<RangeConditionModifier> getConstants() {
    List<RangeConditionModifier> list = new LinkedList<RangeConditionModifier>();
    list.add(RangeConditionModifier.between);
    list.add(RangeConditionModifier.nbetween);
    return list;
  }

  public static RangeConditionModifier getDefault() {
    return RangeConditionModifier.between;
  }

  public static RangeConditionModifier parseValue(String value) {
    if (value == null) {
      return RangeConditionModifier.getDefault();
    }
    if (value.equals(RangeConditionModifier.between.getValueAsString())) {
      return RangeConditionModifier.between;
    }
    if (value.equals(RangeConditionModifier.nbetween.getValueAsString())) {
      return RangeConditionModifier.nbetween;
    }
    return RangeConditionModifier.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
