package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReferenceSimpleExpression extends SimpleExpression {
  public static final String concept = "swiftteams.nikitin.sql.structure.ReferenceSimpleExpression";
  public static final String REFERENCE = "reference";

  public ReferenceSimpleExpression(SNode node) {
    super(node);
  }

  public AbstractTableReference getReference() {
    return (AbstractTableReference)this.getChild(AbstractTableReference.class, ReferenceSimpleExpression.REFERENCE);
  }

  public void setReference(AbstractTableReference node) {
    super.setChild(ReferenceSimpleExpression.REFERENCE, node);
  }


  public static ReferenceSimpleExpression newInstance(SModel sm, boolean init) {
    return (ReferenceSimpleExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ReferenceSimpleExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReferenceSimpleExpression newInstance(SModel sm) {
    return ReferenceSimpleExpression.newInstance(sm, false);
  }

}
