package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RowValues extends Values {
  public static final String concept = "swiftteams.nikitin.sql.structure.RowValues";
  public static final String VALUES = "values";

  public RowValues(SNode node) {
    super(node);
  }

  public int getValuesesCount() {
    return this.getChildCount(RowValues.VALUES);
  }

  public Iterator<Value> valueses() {
    return this.children(Value.class, RowValues.VALUES);
  }

  public List<Value> getValueses() {
    return this.getChildren(Value.class, RowValues.VALUES);
  }

  public void addValues(Value node) {
    this.addChild(RowValues.VALUES, node);
  }

  public void insertValues(Value prev, Value node) {
    this.insertChild(prev, RowValues.VALUES, node);
  }


  public static RowValues newInstance(SModel sm, boolean init) {
    return (RowValues)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.RowValues", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RowValues newInstance(SModel sm) {
    return RowValues.newInstance(sm, false);
  }

}
