package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum SelectModifierData {
  _null_("", " "),
  DISTINCT("DISTINCT", "DISTINCT"),
  ALL("ALL", "ALL"),
  UNIQUE("UNIQUE", "UNIQUE");

  private String myName;
  private String myValue;

  SelectModifierData(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<SelectModifierData> getConstants() {
    List<SelectModifierData> list = new LinkedList<SelectModifierData>();
    list.add(SelectModifierData._null_);
    list.add(SelectModifierData.DISTINCT);
    list.add(SelectModifierData.ALL);
    list.add(SelectModifierData.UNIQUE);
    return list;
  }

  public static SelectModifierData getDefault() {
    return SelectModifierData._null_;
  }

  public static SelectModifierData parseValue(String value) {
    if (value == null) {
      return SelectModifierData.getDefault();
    }
    if (value.equals(SelectModifierData._null_.getValueAsString())) {
      return SelectModifierData._null_;
    }
    if (value.equals(SelectModifierData.DISTINCT.getValueAsString())) {
      return SelectModifierData.DISTINCT;
    }
    if (value.equals(SelectModifierData.ALL.getValueAsString())) {
      return SelectModifierData.ALL;
    }
    if (value.equals(SelectModifierData.UNIQUE.getValueAsString())) {
      return SelectModifierData.UNIQUE;
    }
    return SelectModifierData.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
