package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleComparisonCondition extends Condition {
  public static final String concept = "swiftteams.nikitin.sql.structure.SimpleComparisonCondition";

  public SimpleComparisonCondition(SNode node) {
    super(node);
  }

  public static SimpleComparisonCondition newInstance(SModel sm, boolean init) {
    return (SimpleComparisonCondition)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SimpleComparisonCondition", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SimpleComparisonCondition newInstance(SModel sm) {
    return SimpleComparisonCondition.newInstance(sm, false);
  }

}
