package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;

public class SimpleListComparisonConditionData_PropertySupport extends PropertySupport {

  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<SimpleListComparisonConditionData> constants = SimpleListComparisonConditionData.getConstants().iterator();
    while (constants.hasNext()) {
      SimpleListComparisonConditionData constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }

  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<SimpleListComparisonConditionData> constants = SimpleListComparisonConditionData.getConstants().iterator();
    while (constants.hasNext()) {
      SimpleListComparisonConditionData constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }

  public String fromInternalValue(String value) {
    SimpleListComparisonConditionData constant = SimpleListComparisonConditionData.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }

}
