package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public enum SimpleListComparisonConditionData {
  eq("=", "="),
  ne0("!=", "!="),
  ne1("^=", "^="),
  ne2("<>", "<>");

  private String myName;
  private String myValue;

  SimpleListComparisonConditionData(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public static List<SimpleListComparisonConditionData> getConstants() {
    List<SimpleListComparisonConditionData> list = new LinkedList<SimpleListComparisonConditionData>();
    list.add(SimpleListComparisonConditionData.eq);
    list.add(SimpleListComparisonConditionData.ne0);
    list.add(SimpleListComparisonConditionData.ne1);
    list.add(SimpleListComparisonConditionData.ne2);
    return list;
  }

  public static SimpleListComparisonConditionData getDefault() {
    return SimpleListComparisonConditionData.eq;
  }

  public static SimpleListComparisonConditionData parseValue(String value) {
    if (value == null) {
      return SimpleListComparisonConditionData.getDefault();
    }
    if (value.equals(SimpleListComparisonConditionData.eq.getValueAsString())) {
      return SimpleListComparisonConditionData.eq;
    }
    if (value.equals(SimpleListComparisonConditionData.ne0.getValueAsString())) {
      return SimpleListComparisonConditionData.ne0;
    }
    if (value.equals(SimpleListComparisonConditionData.ne1.getValueAsString())) {
      return SimpleListComparisonConditionData.ne1;
    }
    if (value.equals(SimpleListComparisonConditionData.ne2.getValueAsString())) {
      return SimpleListComparisonConditionData.ne2;
    }
    return SimpleListComparisonConditionData.getDefault();
  }


  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public String getValue() {
    return this.myValue;
  }

}
