package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StarSelectList extends SelectList {
  public static final String concept = "swiftteams.nikitin.sql.structure.StarSelectList";

  public StarSelectList(SNode node) {
    super(node);
  }

  public static StarSelectList newInstance(SModel sm, boolean init) {
    return (StarSelectList)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.StarSelectList", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StarSelectList newInstance(SModel sm) {
    return StarSelectList.newInstance(sm, false);
  }

}
