package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableRow extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableRow";
  public static final String PARAMETERS = "parameters";

  public TableRow(SNode node) {
    super(node);
  }

  public int getParametersesCount() {
    return this.getChildCount(TableRow.PARAMETERS);
  }

  public Iterator<TableRowParameter> parameterses() {
    return this.children(TableRowParameter.class, TableRow.PARAMETERS);
  }

  public List<TableRowParameter> getParameterses() {
    return this.getChildren(TableRowParameter.class, TableRow.PARAMETERS);
  }

  public void addParameters(TableRowParameter node) {
    this.addChild(TableRow.PARAMETERS, node);
  }

  public void insertParameters(TableRowParameter prev, TableRowParameter node) {
    this.insertChild(prev, TableRow.PARAMETERS, node);
  }


  public static TableRow newInstance(SModel sm, boolean init) {
    return (TableRow)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableRow", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableRow newInstance(SModel sm) {
    return TableRow.newInstance(sm, false);
  }

}
