package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableRowsExpressionValue extends Value {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableRowsExpressionValue";
  public static final String EXPRESSION = "expression";

  public TableRowsExpressionValue(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression)this.getChild(Expression.class, TableRowsExpressionValue.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(TableRowsExpressionValue.EXPRESSION, node);
  }


  public static TableRowsExpressionValue newInstance(SModel sm, boolean init) {
    return (TableRowsExpressionValue)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableRowsExpressionValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableRowsExpressionValue newInstance(SModel sm) {
    return TableRowsExpressionValue.newInstance(sm, false);
  }

}
