package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableRows extends Type {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableRows";
  public static final String ROW = "row";

  public TableRows(SNode node) {
    super(node);
  }

  public TableRow getRow() {
    return (TableRow)this.getChild(TableRow.class, TableRows.ROW);
  }

  public void setRow(TableRow node) {
    super.setChild(TableRows.ROW, node);
  }


  public static TableRows newInstance(SModel sm, boolean init) {
    return (TableRows)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableRows", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableRows newInstance(SModel sm) {
    return TableRows.newInstance(sm, false);
  }

}
