package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.AbstractCreator;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableRowsCreator extends AbstractCreator {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableRowsCreator";
  public static final String TYPE = "type";

  public TableRowsCreator(SNode node) {
    super(node);
  }

  public TableRows getType() {
    return (TableRows)this.getChild(TableRows.class, TableRowsCreator.TYPE);
  }

  public void setType(TableRows node) {
    super.setChild(TableRowsCreator.TYPE, node);
  }


  public static TableRowsCreator newInstance(SModel sm, boolean init) {
    return (TableRowsCreator)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableRowsCreator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableRowsCreator newInstance(SModel sm) {
    return TableRowsCreator.newInstance(sm, false);
  }

}
