package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableReferenceSimpleExpressionData extends AbstractTableReferenceSimpleExpressionData {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableReferenceSimpleExpressionData";

  public TableReferenceSimpleExpressionData(SNode node) {
    super(node);
  }

  public static TableReferenceSimpleExpressionData newInstance(SModel sm, boolean init) {
    return (TableReferenceSimpleExpressionData)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableReferenceSimpleExpressionData", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableReferenceSimpleExpressionData newInstance(SModel sm) {
    return TableReferenceSimpleExpressionData.newInstance(sm, false);
  }

}
