package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TextLiteral extends Literal {
  public static final String concept = "swiftteams.nikitin.sql.structure.TextLiteral";
  public static final String TEXT = "text";

  public TextLiteral(SNode node) {
    super(node);
  }

  public String getText() {
    return this.getProperty(TextLiteral.TEXT);
  }

  public void setText(String value) {
    this.setProperty(TextLiteral.TEXT, value);
  }


  public static TextLiteral newInstance(SModel sm, boolean init) {
    return (TextLiteral)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TextLiteral", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TextLiteral newInstance(SModel sm) {
    return TextLiteral.newInstance(sm, false);
  }

}
