package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Value extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.Value";

  public Value(SNode node) {
    super(node);
  }

  public static Value newInstance(SModel sm, boolean init) {
    return (Value)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.Value", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Value newInstance(SModel sm) {
    return Value.newInstance(sm, false);
  }

}
