package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractQuery extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractQuery";

  public AbstractQuery(SNode node) {
    super(node);
  }

  public static AbstractQuery newInstance(SModel sm, boolean init) {
    return (AbstractQuery)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractQuery", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractQuery newInstance(SModel sm) {
    return AbstractQuery.newInstance(sm, false);
  }

}
