package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractJoinedTable extends AbstractTableRef {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractJoinedTable";

  public AbstractJoinedTable(SNode node) {
    super(node);
  }

  public static AbstractJoinedTable newInstance(SModel sm, boolean init) {
    return (AbstractJoinedTable)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractJoinedTable", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractJoinedTable newInstance(SModel sm) {
    return AbstractJoinedTable.newInstance(sm, false);
  }

}
