package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractColumnReference extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractColumnReference";
  public static final String COLUMN = "column";

  public AbstractColumnReference(SNode node) {
    super(node);
  }

  public ColumnRelationalProperty getColumn() {
    return (ColumnRelationalProperty)this.getReferent(ColumnRelationalProperty.class, AbstractColumnReference.COLUMN);
  }

  public void setColumn(ColumnRelationalProperty node) {
    super.setReferent(AbstractColumnReference.COLUMN, node);
  }


  public static AbstractColumnReference newInstance(SModel sm, boolean init) {
    return (AbstractColumnReference)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractColumnReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractColumnReference newInstance(SModel sm) {
    return AbstractColumnReference.newInstance(sm, false);
  }

}
