package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractTableReferenceSimpleExpressionData extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractTableReferenceSimpleExpressionData";
  public static final String COLUMN = "column";

  public AbstractTableReferenceSimpleExpressionData(SNode node) {
    super(node);
  }

  public ColumnRelationalProperty getColumn() {
    return (ColumnRelationalProperty)this.getReferent(ColumnRelationalProperty.class, AbstractTableReferenceSimpleExpressionData.COLUMN);
  }

  public void setColumn(ColumnRelationalProperty node) {
    super.setReferent(AbstractTableReferenceSimpleExpressionData.COLUMN, node);
  }


  public static AbstractTableReferenceSimpleExpressionData newInstance(SModel sm, boolean init) {
    return (AbstractTableReferenceSimpleExpressionData)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractTableReferenceSimpleExpressionData", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractTableReferenceSimpleExpressionData newInstance(SModel sm) {
    return AbstractTableReferenceSimpleExpressionData.newInstance(sm, false);
  }

}
