package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractCaseExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractCaseExpression";

  public AbstractCaseExpression(SNode node) {
    super(node);
  }

  public static AbstractCaseExpression newInstance(SModel sm, boolean init) {
    return (AbstractCaseExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractCaseExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractCaseExpression newInstance(SModel sm) {
    return AbstractCaseExpression.newInstance(sm, false);
  }

}
