package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractTableRef extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractTableRef";

  public AbstractTableRef(SNode node) {
    super(node);
  }

  public static AbstractTableRef newInstance(SModel sm, boolean init) {
    return (AbstractTableRef)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractTableRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractTableRef newInstance(SModel sm) {
    return AbstractTableRef.newInstance(sm, false);
  }

}
