package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AbstractOutLineConstraint extends RelationalProperty {
  public static final String concept = "swiftteams.nikitin.sql.structure.AbstractOutLineConstraint";

  public AbstractOutLineConstraint(SNode node) {
    super(node);
  }

  public static AbstractOutLineConstraint newInstance(SModel sm, boolean init) {
    return (AbstractOutLineConstraint)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.AbstractOutLineConstraint", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AbstractOutLineConstraint newInstance(SModel sm) {
    return AbstractOutLineConstraint.newInstance(sm, false);
  }

}
