package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class BinaryCompoundExpression extends CompoundExpression {
  public static final String concept = "swiftteams.nikitin.sql.structure.BinaryCompoundExpression";
  public static final String LEFT = "left";
  public static final String RIGHT = "right";

  public BinaryCompoundExpression(SNode node) {
    super(node);
  }

  public Expression getLeft() {
    return (Expression)this.getReferent(Expression.class, BinaryCompoundExpression.LEFT);
  }

  public void setLeft(Expression node) {
    super.setReferent(BinaryCompoundExpression.LEFT, node);
  }

  public Expression getRight() {
    return (Expression)this.getReferent(Expression.class, BinaryCompoundExpression.RIGHT);
  }

  public void setRight(Expression node) {
    super.setReferent(BinaryCompoundExpression.RIGHT, node);
  }


  public static BinaryCompoundExpression newInstance(SModel sm, boolean init) {
    return (BinaryCompoundExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.BinaryCompoundExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static BinaryCompoundExpression newInstance(SModel sm) {
    return BinaryCompoundExpression.newInstance(sm, false);
  }

}
