package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompoundSelectListReferenceItem extends AbstractSelectListItem {
  public static final String concept = "swiftteams.nikitin.sql.structure.CompoundSelectListReferenceItem";

  public CompoundSelectListReferenceItem(SNode node) {
    super(node);
  }

  public static CompoundSelectListReferenceItem newInstance(SModel sm, boolean init) {
    return (CompoundSelectListReferenceItem)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CompoundSelectListReferenceItem", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompoundSelectListReferenceItem newInstance(SModel sm) {
    return CompoundSelectListReferenceItem.newInstance(sm, false);
  }

}
