package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompoundSelectListExpressionItem extends AbstractSelectListItem {
  public static final String concept = "swiftteams.nikitin.sql.structure.CompoundSelectListExpressionItem";
  public static final String EXPR = "expr";

  public CompoundSelectListExpressionItem(SNode node) {
    super(node);
  }

  public Expression getExpr() {
    return (Expression)this.getChild(Expression.class, CompoundSelectListExpressionItem.EXPR);
  }

  public void setExpr(Expression node) {
    super.setChild(CompoundSelectListExpressionItem.EXPR, node);
  }


  public static CompoundSelectListExpressionItem newInstance(SModel sm, boolean init) {
    return (CompoundSelectListExpressionItem)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CompoundSelectListExpressionItem", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompoundSelectListExpressionItem newInstance(SModel sm) {
    return CompoundSelectListExpressionItem.newInstance(sm, false);
  }

}
