package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CompoundSelectListTableReferenceItem extends CompoundSelectListReferenceItem {
  public static final String concept = "swiftteams.nikitin.sql.structure.CompoundSelectListTableReferenceItem";
  public static final String REFERENCE = "reference";

  public CompoundSelectListTableReferenceItem(SNode node) {
    super(node);
  }

  public AbstractTableReference getReference() {
    return (AbstractTableReference)this.getChild(AbstractTableReference.class, CompoundSelectListTableReferenceItem.REFERENCE);
  }

  public void setReference(AbstractTableReference node) {
    super.setChild(CompoundSelectListTableReferenceItem.REFERENCE, node);
  }


  public static CompoundSelectListTableReferenceItem newInstance(SModel sm, boolean init) {
    return (CompoundSelectListTableReferenceItem)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.CompoundSelectListTableReferenceItem", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CompoundSelectListTableReferenceItem newInstance(SModel sm) {
    return CompoundSelectListTableReferenceItem.newInstance(sm, false);
  }

}
