package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DateTimeExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.DateTimeExpression";

  public DateTimeExpression(SNode node) {
    super(node);
  }

  public static DateTimeExpression newInstance(SModel sm, boolean init) {
    return (DateTimeExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.DateTimeExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DateTimeExpression newInstance(SModel sm) {
    return DateTimeExpression.newInstance(sm, false);
  }

}
