package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.BooleanConstant;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DeleteQuery extends AbstractQuery {
  public static final String concept = "swiftteams.nikitin.sql.structure.DeleteQuery";
  public static final String HINT = "hint";
  public static final String TABLE = "table";
  public static final String WHERE_CONDITION = "where_condition";
  public static final String RETURNING_CLAUSE = "returning_clause";

  public DeleteQuery(SNode node) {
    super(node);
  }

  public BooleanConstant getHint() {
    return (BooleanConstant)this.getChild(BooleanConstant.class, DeleteQuery.HINT);
  }

  public void setHint(BooleanConstant node) {
    super.setChild(DeleteQuery.HINT, node);
  }

  public TableExpressionClause getTable() {
    return (TableExpressionClause)this.getChild(TableExpressionClause.class, DeleteQuery.TABLE);
  }

  public void setTable(TableExpressionClause node) {
    super.setChild(DeleteQuery.TABLE, node);
  }

  public Condition getWhere_condition() {
    return (Condition)this.getChild(Condition.class, DeleteQuery.WHERE_CONDITION);
  }

  public void setWhere_condition(Condition node) {
    super.setChild(DeleteQuery.WHERE_CONDITION, node);
  }

  public BooleanConstant getReturning_clause() {
    return (BooleanConstant)this.getChild(BooleanConstant.class, DeleteQuery.RETURNING_CLAUSE);
  }

  public void setReturning_clause(BooleanConstant node) {
    super.setChild(DeleteQuery.RETURNING_CLAUSE, node);
  }


  public static DeleteQuery newInstance(SModel sm, boolean init) {
    return (DeleteQuery)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.DeleteQuery", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DeleteQuery newInstance(SModel sm) {
    return DeleteQuery.newInstance(sm, false);
  }

}
