package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DropQueryCascade extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.DropQueryCascade";

  public DropQueryCascade(SNode node) {
    super(node);
  }

  public static DropQueryCascade newInstance(SModel sm, boolean init) {
    return (DropQueryCascade)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.DropQueryCascade", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DropQueryCascade newInstance(SModel sm) {
    return DropQueryCascade.newInstance(sm, false);
  }

}
