package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ExpressionNonListMemberShipCondition extends NonListMembershipCondition {
  public static final String concept = "swiftteams.nikitin.sql.structure.ExpressionNonListMemberShipCondition";
  public static final String EXPRESSIONS = "expressions";

  public ExpressionNonListMemberShipCondition(SNode node) {
    super(node);
  }

  public ExpressionList getExpressions() {
    return (ExpressionList)this.getChild(ExpressionList.class, ExpressionNonListMemberShipCondition.EXPRESSIONS);
  }

  public void setExpressions(ExpressionList node) {
    super.setChild(ExpressionNonListMemberShipCondition.EXPRESSIONS, node);
  }


  public static ExpressionNonListMemberShipCondition newInstance(SModel sm, boolean init) {
    return (ExpressionNonListMemberShipCondition)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ExpressionNonListMemberShipCondition", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ExpressionNonListMemberShipCondition newInstance(SModel sm) {
    return ExpressionNonListMemberShipCondition.newInstance(sm, false);
  }

}
