package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Function extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.Function";

  public Function(SNode node) {
    super(node);
  }

  public static Function newInstance(SModel sm, boolean init) {
    return (Function)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.Function", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Function newInstance(SModel sm) {
    return Function.newInstance(sm, false);
  }

}
