package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class GroupComparisonCondition111 extends Condition {
  public static final String concept = "swiftteams.nikitin.sql.structure.GroupComparisonCondition111";

  public GroupComparisonCondition111(SNode node) {
    super(node);
  }

  public static GroupComparisonCondition111 newInstance(SModel sm, boolean init) {
    return (GroupComparisonCondition111)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.GroupComparisonCondition111", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static GroupComparisonCondition111 newInstance(SModel sm) {
    return GroupComparisonCondition111.newInstance(sm, false);
  }

}
