package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IntegerDataType extends DataType {
  public static final String concept = "swiftteams.nikitin.sql.structure.IntegerDataType";

  public IntegerDataType(SNode node) {
    super(node);
  }

  public static IntegerDataType newInstance(SModel sm, boolean init) {
    return (IntegerDataType)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.IntegerDataType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IntegerDataType newInstance(SModel sm) {
    return IntegerDataType.newInstance(sm, false);
  }

}
