package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class JavaSimpleExpression extends SimpleExpression {
  public static final String concept = "swiftteams.nikitin.sql.structure.JavaSimpleExpression";
  public static final String EXPRESSION = "expression";

  public JavaSimpleExpression(SNode node) {
    super(node);
  }

  public Expression getExpression() {
    return (Expression)this.getChild(Expression.class, JavaSimpleExpression.EXPRESSION);
  }

  public void setExpression(Expression node) {
    super.setChild(JavaSimpleExpression.EXPRESSION, node);
  }


  public static JavaSimpleExpression newInstance(SModel sm, boolean init) {
    return (JavaSimpleExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.JavaSimpleExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static JavaSimpleExpression newInstance(SModel sm) {
    return JavaSimpleExpression.newInstance(sm, false);
  }

}
