package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LiteralInlineConstraintBody extends AbstractInlineConstraintBody {
  public static final String concept = "swiftteams.nikitin.sql.structure.LiteralInlineConstraintBody";
  public static final String MODIFIER = "modifier";

  public LiteralInlineConstraintBody(SNode node) {
    super(node);
  }

  public LiteralConstraintBodyModifierData getModifier() {
    String value = super.getProperty(LiteralInlineConstraintBody.MODIFIER);
    return LiteralConstraintBodyModifierData.parseValue(value);
  }

  public void setModifier(LiteralConstraintBodyModifierData value) {
    super.setProperty(LiteralInlineConstraintBody.MODIFIER, value.getValueAsString());
  }


  public static LiteralInlineConstraintBody newInstance(SModel sm, boolean init) {
    return (LiteralInlineConstraintBody)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.LiteralInlineConstraintBody", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LiteralInlineConstraintBody newInstance(SModel sm) {
    return LiteralInlineConstraintBody.newInstance(sm, false);
  }

}
