package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NullCondition extends Condition {
  public static final String concept = "swiftteams.nikitin.sql.structure.NullCondition";
  public static final String MODIFIER = "modifier";
  public static final String EXPR = "expr";

  public NullCondition(SNode node) {
    super(node);
  }

  public NullConditionModifier getModifier() {
    String value = super.getProperty(NullCondition.MODIFIER);
    return NullConditionModifier.parseValue(value);
  }

  public void setModifier(NullConditionModifier value) {
    super.setProperty(NullCondition.MODIFIER, value.getValueAsString());
  }

  public Expression getExpr() {
    return (Expression)this.getChild(Expression.class, NullCondition.EXPR);
  }

  public void setExpr(Expression node) {
    super.setChild(NullCondition.EXPR, node);
  }


  public static NullCondition newInstance(SModel sm, boolean init) {
    return (NullCondition)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.NullCondition", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NullCondition newInstance(SModel sm) {
    return NullCondition.newInstance(sm, false);
  }

}
