package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class OrderByClause extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.OrderByClause";
  public static final String EXPRESSIONS = "expressions";

  public OrderByClause(SNode node) {
    super(node);
  }

  public int getExpressionsesCount() {
    return this.getChildCount(OrderByClause.EXPRESSIONS);
  }

  public Iterator<Expression> expressionses() {
    return this.children(Expression.class, OrderByClause.EXPRESSIONS);
  }

  public List<Expression> getExpressionses() {
    return this.getChildren(Expression.class, OrderByClause.EXPRESSIONS);
  }

  public void addExpressions(Expression node) {
    this.addChild(OrderByClause.EXPRESSIONS, node);
  }

  public void insertExpressions(Expression prev, Expression node) {
    this.insertChild(prev, OrderByClause.EXPRESSIONS, node);
  }


  public static OrderByClause newInstance(SModel sm, boolean init) {
    return (OrderByClause)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.OrderByClause", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static OrderByClause newInstance(SModel sm) {
    return OrderByClause.newInstance(sm, false);
  }

}
