package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Expression;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class QuerySheet extends BaseConcept implements INamedConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.QuerySheet";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String DRIVER = "driver";
  public static final String URL = "url";
  public static final String LOGIN = "login";
  public static final String PASSWORD = "password";
  public static final String QUERIES = "queries";

  public QuerySheet(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(QuerySheet.NAME);
  }

  public void setName(String value) {
    this.setProperty(QuerySheet.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(QuerySheet.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(QuerySheet.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(QuerySheet.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(QuerySheet.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(QuerySheet.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(QuerySheet.VIRTUAL_PACKAGE, value);
  }

  public Expression getDriver() {
    return (Expression)this.getChild(Expression.class, QuerySheet.DRIVER);
  }

  public void setDriver(Expression node) {
    super.setChild(QuerySheet.DRIVER, node);
  }

  public Expression getUrl() {
    return (Expression)this.getChild(Expression.class, QuerySheet.URL);
  }

  public void setUrl(Expression node) {
    super.setChild(QuerySheet.URL, node);
  }

  public Expression getLogin() {
    return (Expression)this.getChild(Expression.class, QuerySheet.LOGIN);
  }

  public void setLogin(Expression node) {
    super.setChild(QuerySheet.LOGIN, node);
  }

  public Expression getPassword() {
    return (Expression)this.getChild(Expression.class, QuerySheet.PASSWORD);
  }

  public void setPassword(Expression node) {
    super.setChild(QuerySheet.PASSWORD, node);
  }

  public int getQueriesesCount() {
    return this.getChildCount(QuerySheet.QUERIES);
  }

  public Iterator<AbstractQuery> querieses() {
    return this.children(AbstractQuery.class, QuerySheet.QUERIES);
  }

  public List<AbstractQuery> getQuerieses() {
    return this.getChildren(AbstractQuery.class, QuerySheet.QUERIES);
  }

  public void addQueries(AbstractQuery node) {
    this.addChild(QuerySheet.QUERIES, node);
  }

  public void insertQueries(AbstractQuery prev, AbstractQuery node) {
    this.insertChild(prev, QuerySheet.QUERIES, node);
  }


  public static QuerySheet newInstance(SModel sm, boolean init) {
    return (QuerySheet)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.QuerySheet", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static QuerySheet newInstance(SModel sm) {
    return QuerySheet.newInstance(sm, false);
  }

}
