package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReferenceTableExpressionClause extends TableExpressionClause {
  public static final String concept = "swiftteams.nikitin.sql.structure.ReferenceTableExpressionClause";
  public static final String REFERENCE = "reference";

  public ReferenceTableExpressionClause(SNode node) {
    super(node);
  }

  public AbstractTableReference getReference() {
    return (AbstractTableReference)this.getChild(AbstractTableReference.class, ReferenceTableExpressionClause.REFERENCE);
  }

  public void setReference(AbstractTableReference node) {
    super.setChild(ReferenceTableExpressionClause.REFERENCE, node);
  }


  public static ReferenceTableExpressionClause newInstance(SModel sm, boolean init) {
    return (ReferenceTableExpressionClause)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.ReferenceTableExpressionClause", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReferenceTableExpressionClause newInstance(SModel sm) {
    return ReferenceTableExpressionClause.newInstance(sm, false);
  }

}
