package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RelationalProperty extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.RelationalProperty";

  public RelationalProperty(SNode node) {
    super(node);
  }

  public static RelationalProperty newInstance(SModel sm, boolean init) {
    return (RelationalProperty)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.RelationalProperty", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RelationalProperty newInstance(SModel sm) {
    return RelationalProperty.newInstance(sm, false);
  }

}
