package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SchemaObject extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.SchemaObject";

  public SchemaObject(SNode node) {
    super(node);
  }

  public static SchemaObject newInstance(SModel sm, boolean init) {
    return (SchemaObject)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SchemaObject", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SchemaObject newInstance(SModel sm) {
    return SchemaObject.newInstance(sm, false);
  }

}
