package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SelectList extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.SelectList";

  public SelectList(SNode node) {
    super(node);
  }

  public static SelectList newInstance(SModel sm, boolean init) {
    return (SelectList)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SelectList", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SelectList newInstance(SModel sm) {
    return SelectList.newInstance(sm, false);
  }

}
