package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SimpleExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.SimpleExpression";

  public SimpleExpression(SNode node) {
    super(node);
  }

  public static SimpleExpression newInstance(SModel sm, boolean init) {
    return (SimpleExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SimpleExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SimpleExpression newInstance(SModel sm) {
    return SimpleExpression.newInstance(sm, false);
  }

}
