package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SingleTableInsert extends TableInsert {
  public static final String concept = "swiftteams.nikitin.sql.structure.SingleTableInsert";
  public static final String INSERT_INTO_CLAUSE = "insert_into_clause";

  public SingleTableInsert(SNode node) {
    super(node);
  }

  public InsertIntoClause getInsert_into_clause() {
    return (InsertIntoClause)this.getChild(InsertIntoClause.class, SingleTableInsert.INSERT_INTO_CLAUSE);
  }

  public void setInsert_into_clause(InsertIntoClause node) {
    super.setChild(SingleTableInsert.INSERT_INTO_CLAUSE, node);
  }


  public static SingleTableInsert newInstance(SModel sm, boolean init) {
    return (SingleTableInsert)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SingleTableInsert", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SingleTableInsert newInstance(SModel sm) {
    return SingleTableInsert.newInstance(sm, false);
  }

}
