package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Sql_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("3dfc950c-a09a-4cd2-af77-badd0bdf2723(swiftteams.nikitin.sql)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }

}
