package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.BooleanConstant;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SubQueryTableExpressionClause extends TableExpressionClause {
  public static final String concept = "swiftteams.nikitin.sql.structure.SubQueryTableExpressionClause";
  public static final String SUBQUERY = "subquery";
  public static final String SUBQUERY_RESTRICTION_CLAUSE = "subquery_restriction_clause";

  public SubQueryTableExpressionClause(SNode node) {
    super(node);
  }

  public SubQuery getSubquery() {
    return (SubQuery)this.getChild(SubQuery.class, SubQueryTableExpressionClause.SUBQUERY);
  }

  public void setSubquery(SubQuery node) {
    super.setChild(SubQueryTableExpressionClause.SUBQUERY, node);
  }

  public BooleanConstant getSubquery_restriction_clause() {
    return (BooleanConstant)this.getChild(BooleanConstant.class, SubQueryTableExpressionClause.SUBQUERY_RESTRICTION_CLAUSE);
  }

  public void setSubquery_restriction_clause(BooleanConstant node) {
    super.setChild(SubQueryTableExpressionClause.SUBQUERY_RESTRICTION_CLAUSE, node);
  }


  public static SubQueryTableExpressionClause newInstance(SModel sm, boolean init) {
    return (SubQueryTableExpressionClause)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SubQueryTableExpressionClause", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SubQueryTableExpressionClause newInstance(SModel sm) {
    return SubQueryTableExpressionClause.newInstance(sm, false);
  }

}
