package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SubQueryNonListMembershipCondition extends NonListMembershipCondition {
  public static final String concept = "swiftteams.nikitin.sql.structure.SubQueryNonListMembershipCondition";
  public static final String SUBQUERY = "subquery";

  public SubQueryNonListMembershipCondition(SNode node) {
    super(node);
  }

  public SubQuery getSubquery() {
    return (SubQuery)this.getChild(SubQuery.class, SubQueryNonListMembershipCondition.SUBQUERY);
  }

  public void setSubquery(SubQuery node) {
    super.setChild(SubQueryNonListMembershipCondition.SUBQUERY, node);
  }


  public static SubQueryNonListMembershipCondition newInstance(SModel sm, boolean init) {
    return (SubQueryNonListMembershipCondition)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.SubQueryNonListMembershipCondition", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SubQueryNonListMembershipCondition newInstance(SModel sm) {
    return SubQueryNonListMembershipCondition.newInstance(sm, false);
  }

}
