package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableRowParameter extends BaseConcept {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableRowParameter";

  public TableRowParameter(SNode node) {
    super(node);
  }

  public static TableRowParameter newInstance(SModel sm, boolean init) {
    return (TableRowParameter)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableRowParameter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableRowParameter newInstance(SModel sm) {
    return TableRowParameter.newInstance(sm, false);
  }

}
