package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TableReferenceSimpleExpression extends ReferenceSimpleExpression {
  public static final String concept = "swiftteams.nikitin.sql.structure.TableReferenceSimpleExpression";
  public static final String DATA = "data";

  public TableReferenceSimpleExpression(SNode node) {
    super(node);
  }

  public AbstractTableReferenceSimpleExpressionData getData() {
    return (AbstractTableReferenceSimpleExpressionData)this.getChild(AbstractTableReferenceSimpleExpressionData.class, TableReferenceSimpleExpression.DATA);
  }

  public void setData(AbstractTableReferenceSimpleExpressionData node) {
    super.setChild(TableReferenceSimpleExpression.DATA, node);
  }


  public static TableReferenceSimpleExpression newInstance(SModel sm, boolean init) {
    return (TableReferenceSimpleExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.TableReferenceSimpleExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TableReferenceSimpleExpression newInstance(SModel sm) {
    return TableReferenceSimpleExpression.newInstance(sm, false);
  }

}
