package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UnaryCompoundExpression extends CompoundExpression {
  public static final String concept = "swiftteams.nikitin.sql.structure.UnaryCompoundExpression";
  public static final String EXPR = "expr";

  public UnaryCompoundExpression(SNode node) {
    super(node);
  }

  public Expression getExpr() {
    return (Expression)this.getReferent(Expression.class, UnaryCompoundExpression.EXPR);
  }

  public void setExpr(Expression node) {
    super.setReferent(UnaryCompoundExpression.EXPR, node);
  }


  public static UnaryCompoundExpression newInstance(SModel sm, boolean init) {
    return (UnaryCompoundExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.UnaryCompoundExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UnaryCompoundExpression newInstance(SModel sm) {
    return UnaryCompoundExpression.newInstance(sm, false);
  }

}
