package swiftteams.nikitin.sql.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class VariableExpression extends Expression {
  public static final String concept = "swiftteams.nikitin.sql.structure.VariableExpression";

  public VariableExpression(SNode node) {
    super(node);
  }

  public static VariableExpression newInstance(SModel sm, boolean init) {
    return (VariableExpression)SModelUtil_new.instantiateConceptDeclaration("swiftteams.nikitin.sql.structure.VariableExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static VariableExpression newInstance(SModel sm) {
    return VariableExpression.newInstance(sm, false);
  }

}
