package swiftteams.nikitin.sql.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.typesystem.inference.TypeChecker;
import jetbrains.mps.project.GlobalScope;
import jetbrains.mps.smodel.SReference;
import jetbrains.mps.smodel.SModelReference;
import jetbrains.mps.smodel.SNodeId;

public class _Quotations {

  public _Quotations() {
  }
  public static class QuotationClass_0 {

    public QuotationClass_0() {
    }

    public SNode createNode() {
      SNode result = null;
      SNode quotedNode_0 = null;
      {
        quotedNode_0 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StaticFieldReference", TypeChecker.getInstance().getRuntimeTypesModel(), GlobalScope.getInstance(), false);
        SNode quotedNode1_0 = quotedNode_0;
        quotedNode1_0.addReference(SReference.create("variableDeclaration", quotedNode1_0, SModelReference.fromString("f:java_stub#java.lang(java.lang@java_stub)"), SNodeId.fromString("~Integer.TYPE")));
        quotedNode1_0.addReference(SReference.create("classifier", quotedNode1_0, SModelReference.fromString("r:74249faa-0653-4ad1-8637-371425473c8b(swiftteams.nikitin.sql.runtime)"), SNodeId.fromString("1217507042344")));
        result = quotedNode1_0;
      }
      return result;
    }

}
  public static class QuotationClass_1 {

    public QuotationClass_1() {
    }

    public SNode createNode() {
      SNode result = null;
      SNode quotedNode_1 = null;
      {
        quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baseLanguage.structure.StaticFieldReference", TypeChecker.getInstance().getRuntimeTypesModel(), GlobalScope.getInstance(), false);
        SNode quotedNode1_1 = quotedNode_1;
        quotedNode1_1.addReference(SReference.create("variableDeclaration", quotedNode1_1, SModelReference.fromString("f:java_stub#java.lang(java.lang@java_stub)"), SNodeId.fromString("~Integer.TYPE")));
        quotedNode1_1.addReference(SReference.create("classifier", quotedNode1_1, SModelReference.fromString("f:java_stub#java.lang(java.lang@java_stub)"), SNodeId.fromString("~Iterable")));
        result = quotedNode1_1;
      }
      return result;
    }

}

}
