package swiftteams.nikitin.sql.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ColumnRelationalProperty_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(thisNode), "swiftteams.nikitin.sql.structure.RelationalCreateQuery"), "name") + '.' + SPropertyOperations.getString(thisNode, "columnName");
  }

}
