package swiftteams.nikitin.sql.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class DeclarationTableRowParameter_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "datatype", true), "alias") + ' ' + SPropertyOperations.getString(thisNode, "variable_name");
  }

}
