package swiftteams.nikitin.sql.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.core.behavior.BaseConcept_Behavior;

public class TableRows_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    StringBuilder sb = new StringBuilder("TableRows <");
    for(SNode parameter : ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "row", true), "parameters", true))) {
      if (SNodeOperations.getIndexInParent(parameter) != 0) {
        sb.append(", ");
      }
      sb.append(BaseConcept_Behavior.call_getPresentation_1213877396640(parameter));
    }
    return sb.append('>').toString();
  }

  public static SNode virtual_getClassExpression_1213877337357(SNode thisNode) {
    return new _Quotations.QuotationClass_1().createNode();
  }

}
