package swiftteams.nikitin.sql.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class VoidFunctionExpression_Behavior {

  public static void init(SNode thisNode) {
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return "TIMESTAMP";
  }

}
