package swiftteams.nikitin.sql.generator.baseLanguage.template.tablerows.util;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;

public class ConnectionManager {
  public static Connection connection;

  public static void setConnection(String driver, String url) {
    // true creation of connection :-)
    try {
      Class.forName(driver);
    } catch (ClassNotFoundException cnfe) {
    }
    try {
      connection = DriverManager.getConnection(url);
    } catch (SQLException se) {
      connection = null;
    }
  }

  public static Connection getConnection() {
    // here must be only "return connection;" line
    try {
      Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
    } catch (ClassNotFoundException cnfe) {
    }
    try {
      return DriverManager.getConnection("jdbc:derby:TEST");
    } catch (SQLException se) {
      return null;
    }
  }

  public static ResultSet executeQuery(String query) throws SQLException {
    return connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY).executeQuery(query);
  }

}
