package swiftteams.nikitin.sql.generator.baseLanguage.template.tablerows.util;

/*Generated by MPS */

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Iterator;

public class IterableResultSet implements Iterable<TableRow> {

  private ResultSet resultSet;
  private int size;
  private TableRow[] rows;

  public IterableResultSet(ResultSet resultSet) {
    try {
      this.resultSet = resultSet;
      this.size = resultSet.getFetchSize();
      this.rows = new TableRow[this.size];
    } catch (SQLException se) {
    }
  }

  public Iterator<TableRow> iterator() {
    return new TableRowIterator(this);
  }

  public int getSize() {
    return this.size;
  }

  /* package */TableRow getRow(int position) {
    try {
      this.resultSet.absolute(position);
      if (this.rows[position] == null) {
        this.rows[position] = new TableRow(this.resultSet);
      }
      return this.rows[position];
    } catch (SQLException se) {
      return null;
    }
  }

}
