package swiftteams.nikitin.sql.generator.baseLanguage.template.tablerows.util;

/*Generated by MPS */

import java.util.Iterator;

public class TableRowIterator implements Iterator<TableRow> {

  private IterableResultSet parent;
  private int position = 0;

  public TableRowIterator(IterableResultSet parent) {
    this.parent = parent;
  }

  public boolean hasNext() {
    return this.position < this.parent.getSize();
  }

  public TableRow next() {
    TableRow result = this.parent.getRow(this.position);
    this.position = this.position + 1;
    return result;
  }

  public void remove() {
    throw new IllegalStateException();
  }

}
