package swiftteams.nikitin.sqlserver;

/*Generated by MPS */

import java.sql.SQLException;
import java.util.List;
import swiftteams.nikitin.sql.runtime.TableRow;

public interface ILogic {

  public abstract int login(String login, int pw_hash) throws SQLException;

  public abstract void logout(int id) throws SQLException;

  public abstract List<TableRow> userStats(int id) throws SQLException;

  public abstract boolean isAdmin(int id) throws SQLException;

}
