package swiftteams.nikitin.sqlserver;

/*Generated by MPS */

import swiftteams.nikitin.sql.runtime.ConnectionManager;
import java.sql.SQLException;

public class Schema {

  public static void main(String[] args) {
    try {
      ConnectionManager.setConnection("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/server", "Morj", "mrj");
      ConnectionManager.update("DROP TABLE stats");
      ConnectionManager.update("DROP TABLE admins");
      ConnectionManager.update("DROP TABLE accounts");
      ConnectionManager.update("CREATE TABLE " + "accounts" + "(" + "id INTEGER  PRIMARY KEY" + ",\n            " + "login" + " " + "VARCHAR (256)" + "  NOT NULL" + ",\n            " + "pw_hash INTEGER " + ",\n            " + "UNIQUE (" + "" + "login" + ")" + ")");
      ConnectionManager.update("CREATE TABLE " + "admins" + "(" + "id INTEGER  PRIMARY KEY" + ",\n            " + "FOREIGN KEY (" + "" + "id" + ") " + "" + "REFERENCES accounts (" + "" + "id" + ")" + ")");
      ConnectionManager.update("CREATE TABLE " + "stats" + "(" + "id INTEGER  NOT NULL" + ",\n            " + "action" + " " + "VARCHAR (256)" + "  NOT NULL" + ",\n            " + "timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL" + ",\n            " + "FOREIGN KEY (" + "" + "id" + ") " + "" + "REFERENCES accounts (" + "" + "id" + ")" + ",\n            " + "PRIMARY KEY (" + "" + "id,action,timestamp" + ")" + ")");
      ConnectionManager.update("INSERT " + "INTO accounts (" + "" + "id,login,pw_hash" + ")" + " VALUES" + "" + "(" + "" + 1 + ",'user1'" + "," + 1 + ")" + "," + "(" + "" + 2 + ",'user2'" + "," + 2 + ")");
      ConnectionManager.shutdown();
      System.out.println("database init successfully done!");
    } catch (SQLException se) {
      System.out.print("database init error:");
      se.printStackTrace();
    }
  }

}
